# Generated by Django 5.2.3 on 2025-06-15 01:02

import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("meta", "Meta (Facebook/Instagram)"),
                            ("tiktok", "TikTok"),
                            ("google", "Google Ads"),
                            ("x", "Twitter/X"),
                            ("others", "Others"),
                        ],
                        max_length=50,
                    ),
                ),
                ("audience", models.JSONField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "budget",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("campaign_files", models.JSONField(blank=True, default=list)),
                ("result_metrics", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("active", models.BooleanField(default=False)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="AudienceSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, max_length=2000, null=True),
                ),
                ("interests", models.JSONField(blank=True, default=list)),
                ("demographics", models.JSONField(blank=True, default=dict)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("meta", "Meta (Facebook/Instagram)"),
                            ("tiktok", "TikTok"),
                            ("google", "Google Ads"),
                            ("x", "Twitter/X"),
                            ("others", "Others"),
                        ],
                        max_length=100,
                    ),
                ),
                ("lookalike_score", models.FloatField(default=0.0)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audiences",
                        to="agent.campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdCreative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creative_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=50
                    ),
                ),
                ("file_url", models.URLField()),
                ("prompt_used", models.TextField(blank=True, null=True)),
                ("performance_metrics", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creatives",
                        to="agent.campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OptimizationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("action", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True, null=True)),
                ("metrics_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="optimization_logs",
                        to="agent.campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "product_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None, length=7, max_length=20, prefix="", unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=2000, null=True),
                ),
                ("features", models.JSONField(blank=True, default=list, null=True)),
                (
                    "product_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("url", models.URLField(blank=True, max_length=500, null=True)),
                ("image", models.ImageField(upload_to="products/images/")),
                (
                    "files",
                    models.FileField(
                        blank=True, null=True, upload_to="products/files/"
                    ),
                ),
                ("media_assets", models.JSONField(blank=True, default=list, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agent.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="agent.tag"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="campaign",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to="agent.product",
            ),
        ),
        migrations.CreateModel(
            name="PromptLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField(blank=True, max_length=2000, null=True)),
                ("response", models.TextField(blank=True, max_length=2000, null=True)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
