# Generated by Django 5.2.3 on 2025-06-18 15:21

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdsCreatives",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creative_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("carousel", "Carousel"),
                            ("audio", "Audio"),
                            ("text", "Text"),
                            ("story", "Story"),
                            ("reel", "Reel"),
                            ("adset", "Adset"),
                            ("ad", "Ad"),
                            ("adgroup", "Adgroup"),
                            ("adset", "Adset"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file_url", models.URLField()),
                ("prompt_used", models.TextField(blank=True, null=True)),
                ("audience", models.JSONField(blank=True, default=dict)),
                ("performance_metrics", models.JSONField(blank=True, default=dict)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "creative_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None, length=7, max_length=20, prefix="", unique=True
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="campaign",
            name="objective",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="product_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paused", "Paused"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("failed", "Failed"),
                    ("archived", "Archived"),
                    ("deleted", "Deleted"),
                    ("suspended", "Suspended"),
                    ("expired", "Expired"),
                ],
                default="paused",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="campaign_files",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/images/"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="creatives",
            field=models.ManyToManyField(
                blank=True, related_name="campaigns", to="agent.adscreatives"
            ),
        ),
        migrations.DeleteModel(
            name="AdCreative",
        ),
    ]
