# Generated by Django 5.2.3 on 2025-06-20 16:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0002_adscreatives_campaign_objective_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiencesegment",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="segments",
                to="agent.campaign",
            ),
        ),
        migrations.CreateModel(
            name="CampaignSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audience", models.JSONField(blank=True, default=dict)),
                ("ad_formats", models.JSONField(blank=True, default=list)),
                ("campaign_description", models.TextField(blank=True, null=True)),
                ("headline", models.CharField(blank=True, max_length=255, null=True)),
                ("cta", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="agent.campaign",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="agent.product"
                    ),
                ),
            ],
        ),
    ]
