# Generated by Django 5.2.3 on 2025-06-20 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0003_alter_audiencesegment_campaign_campaignsummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="ad_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="ad_type_subtypes",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="audiencesegment",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audiences",
                to="agent.campaign",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paused", "Paused"),
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("failed", "Failed"),
                    ("archived", "Archived"),
                    ("deleted", "Deleted"),
                    ("suspended", "Suspended"),
                    ("expired", "Expired"),
                ],
                default="paused",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="campaignsummary",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaign_summary",
                to="agent.campaign",
            ),
        ),
    ]
