# Generated by Django 5.2.3 on 2025-06-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0004_campaign_ad_type_campaign_ad_type_subtypes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiencesegment",
            name="platform",
            field=models.CharField(max_length=100),
        ),
    ]
