# Generated by Django 5.2.3 on 2025-06-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0005_alter_audiencesegment_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="platform",
            field=models.CharField(max_length=50),
        ),
    ]
