# Generated by Django 5.2.3 on 2025-06-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0006_alter_campaign_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="all_platform",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
