# Generated by Django 5.2.3 on 2025-06-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0007_campaign_all_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="benefits",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="useCases",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
