# Generated by Django 5.2.3 on 2025-06-20 23:55

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0008_product_benefits_product_usecases"),
    ]

    operations = [
        migrations.RenameField(
            model_name="adscreatives",
            old_name="prompt_used",
            new_name="ad_copy",
        ),
        migrations.RemoveField(
            model_name="adscreatives",
            name="audience",
        ),
        migrations.AddField(
            model_name="adscreatives",
            name="cta",
            field=models.CharField(default="Learn More", max_length=100),
        ),
        migrations.AddField(
            model_name="adscreatives",
            name="headline",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="adscreatives",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="adscreatives",
            name="platform",
            field=models.CharField(
                blank=True,
                choices=[
                    ("meta", "Meta (Facebook/Instagram)"),
                    ("tiktok", "TikTok"),
                    ("google", "Google Ads"),
                    ("x", "Twitter/X"),
                    ("others", "Others"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="adscreatives",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="agent.product",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="ad_copy",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="cta",
            field=models.CharField(default="Learn More", max_length=100),
        ),
        migrations.AddField(
            model_name="campaign",
            name="headline",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="adscreatives",
            name="creative_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
