# Generated by Django 5.2.3 on 2025-06-20 23:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0009_rename_prompt_used_adscreatives_ad_copy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adscreatives",
            name="file_url",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
