# Generated by Django 5.2.3 on 2025-06-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0010_alter_adscreatives_file_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adscreatives",
            name="platform",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
