# Generated by Django 5.2.3 on 2025-06-21 22:26

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0011_alter_adscreatives_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="campaign_id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None, length=7, max_length=20, prefix="", unique=True
            ),
        ),
    ]
