# Generated by Django 5.2.3 on 2025-06-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0012_campaign_campaign_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="budget",
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=12),
        ),
    ]
