# Generated by Django 5.2.3 on 2025-06-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0013_product_budget"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaignsummary",
            name="campaign_description",
        ),
        migrations.AddField(
            model_name="campaign",
            name="meta_campaign_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="campaignsummary",
            name="campaign_general_summary",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
