# Generated by Django 5.2.3 on 2025-06-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0014_remove_campaignsummary_campaign_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adscreatives",
            name="file_hash",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
