# Generated by Django 5.2.3 on 2025-06-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0015_adscreatives_file_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="purchase_roas",
            field=models.CharField(blank=True, null=True),
        ),
    ]
