# Generated by Django 5.2.3 on 2025-06-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0016_campaign_purchase_roas"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="purchases",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="revenue",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="purchase_roas",
            field=models.FloatField(default=0.0),
        ),
    ]
