# Generated by Django 5.2.3 on 2025-06-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0017_campaign_purchases_campaign_revenue_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="conversion_rate",
            field=models.FloatField(default=0.0),
        ),
    ]
