# Generated by Django 5.2.3 on 2025-06-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0018_campaign_conversion_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="meta_adset_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
