# Generated by Django 5.2.3 on 2025-06-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0019_campaign_meta_adset_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="optimizationlog",
            name="creative_used",
            field=models.ManyToManyField(
                blank=True, related_name="optimization_logs", to="agent.adscreatives"
            ),
        ),
        migrations.AddField(
            model_name="optimizationlog",
            name="reason",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="optimizationlog",
            name="action",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
