# Generated by Django 5.2.3 on 2025-06-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0020_optimizationlog_creative_used_optimizationlog_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="value",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
