# Generated by Django 5.2.3 on 2025-06-28 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0021_product_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="optimizationlog",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="agent.product",
            ),
        ),
    ]
