# Generated by Django 5.2.3 on 2025-06-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0022_optimizationlog_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adscreatives",
            name="cta",
            field=models.CharField(default="Buy Now", max_length=100),
        ),
    ]
