# Generated by Django 5.2.3 on 2025-07-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0023_alter_adscreatives_cta"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="meta_creative_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
