# Generated by Django 5.2.3 on 2025-07-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0024_campaign_meta_creative_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="meta_ad_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
