# Generated by Django 5.2.3 on 2025-07-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0025_campaign_meta_ad_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("niche", models.CharField(blank=True, max_length=255, null=True)),
                ("source_url", models.URLField(blank=True, null=True)),
                (
                    "gpt_subject",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("gpt_message", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("scraped", "Scraped"),
                            ("email_generated", "Email Generated"),
                            ("sent", "Sent"),
                            ("replied", "Replied"),
                            ("converted", "Converted"),
                            ("failed", "Failed"),
                        ],
                        default="new",
                        max_length=50,
                    ),
                ),
                ("last_contacted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
