# Generated by Django 5.2.3 on 2025-07-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0026_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="source_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
