# Generated by Django 5.2.3 on 2025-07-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0027_lead_source_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
