# Generated by Django 5.2.3 on 2025-07-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0028_lead_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="external_urls",
            field=models.TextField(blank=True, null=True),
        ),
    ]
