# Generated by Django 5.2.3 on 2025-07-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0029_lead_external_urls"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lead",
            old_name="description",
            new_name="bio",
        ),
        migrations.AddField(
            model_name="lead",
            name="business_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
