# Generated by Django 5.2.3 on 2025-07-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0030_rename_description_lead_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
