# Generated by Django 5.2.3 on 2025-07-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0031_alter_lead_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainHealthCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=100)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "spam_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Score from 0–10 (Mail-Tester)",
                        max_digits=4,
                    ),
                ),
                ("is_blacklisted", models.BooleanField(default=False)),
                ("spf_valid", models.BooleanField(default=False)),
                ("dkim_valid", models.BooleanField(default=False)),
                ("dmarc_valid", models.BooleanField(default=False)),
                (
                    "tool_used",
                    models.CharField(
                        help_text="e.g., Mail-Tester, MXToolbox, GMass", max_length=100
                    ),
                ),
                ("report_link", models.URLField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmailWarmupLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("sender_email", models.EmailField(max_length=254)),
                ("emails_sent", models.PositiveIntegerField(default=0)),
                ("inboxed", models.PositiveIntegerField(default=0)),
                ("spam", models.PositiveIntegerField(default=0)),
                ("replies_received", models.PositiveIntegerField(default=0)),
                (
                    "inboxes_tested",
                    models.TextField(help_text="Comma-separated: Gmail, Yahoo, etc."),
                ),
                ("notes", models.TextField(blank=True)),
            ],
        ),
    ]
