# Generated by Django 5.2.3 on 2025-07-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0032_domainhealthcheck_emailwarmuplog"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="opened",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="responded",
            field=models.BooleanField(default=False),
        ),
    ]
