# Generated by Django 5.2.3 on 2025-07-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0033_lead_email_sent_lead_opened_lead_responded"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
