# Generated by Django 5.2.3 on 2025-07-10 16:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0034_lead_company_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lead",
            old_name="gpt_message",
            new_name="outreach_email",
        ),
    ]
