# Generated by Django 5.2.3 on 2025-07-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0035_rename_gpt_message_lead_outreach_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="email_provider_used",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
