# Generated by Django 5.2.3 on 2025-07-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0036_lead_email_provider_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="opened_at",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
