# Generated by Django 5.2.3 on 2025-07-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0037_lead_opened_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="valid",
            field=models.BooleanField(default=False),
        ),
    ]
