# Generated by Django 5.2.3 on 2025-07-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0038_lead_valid"),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email_provider_used',
            field=models.CharField(max_length=255, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='opened_at',
            field=models.CharField(max_length=255, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source_name',
            field=models.CharField(max_length=255, blank=True, null=True),
        ),
    ]
