# Generated by Django 5.2.3 on 2025-07-21 20:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0038_lead_valid"),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE agent_lead ALTER COLUMN email_provider_used TYPE VARCHAR(255);"),
        migrations.RunSQL("ALTER TABLE agent_lead ALTER COLUMN opened_at TYPE VARCHAR(255);"),
        migrations.RunSQL("ALTER TABLE agent_lead ALTER COLUMN source_name TYPE VARCHAR(255);"),
    ]