# Generated by Django 5.2.3 on 2025-07-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0039_fix_field_lengths"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="followup_sent",
            field=models.BooleanField(default=False),
        ),
    ]
