# Generated by Django 5.2.3 on 2025-07-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0040_lead_followup_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="phone",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
