# Generated by Django 5.2.3 on 2025-07-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0041_lead_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="address",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
